### ISSUE TITLE
Estimate position on the road from lane markings

### ISSUE THREAD

**Issue by Goldob** [KNR-Selfie/selfie_carolocup2019#29]
Implement node `estimate_position` in package `selfie_path_planner`, which given a set of road markings detections will be able to estimate the vehicle's position with respect to the right lane of the road. This node should assume perfect detection independent of special conditions, such as dashed lines, missing markings etc.

### Subscribed topics

`road_markings` ([selfie_msgs/RoadMarkings](https://github.com/KNR-Selfie/selfie_carolocup2019/blob/develop/src/selfie_msgs/msg/RoadMarkings.msg))
Position of road markings, given as lists of points in local coordinate system of the vehicle.

### Published topics

`position_offset` ([std_msgs/Float64](http://docs.ros.org/lunar/api/std_msgs/html/msg/Float64.html))
Distance from the center of the right lane (in meters). Positive offset is to the left.

`heading_offset` ([std_msgs/Float64](http://docs.ros.org/lunar/api/std_msgs/html/msg/Float64.html))
Angle between the vehicle's direction and the tangent to the road (in radians), normalized between -π and π. Positive offset is to the left.

**Comment by matmarczuk** [comment]
I assume we will be able to implement whole path_planning module. My suggestion is to create that node in package path_planner and in package selfie_perception place nodes which have to deal with hardware (Camera, Lidar etc.).

**Comment by Goldob** [comment]
Fair point. Specification updated.

**Comment by Goldob** [comment]
What's left to do is change name of the node according to specification (`estimate_position`) and put documentation inside the package directory. I will handle it, but until then the issue is not resolved.

**Comment by Goldob** [comment]
Also, the package should work in the correct coordinate system when working with `road_markings` topic.

**Comment by matmarczuk** [comment]
I've changed pck and node names. Changes are commited on new branch starting_procedure
