### ISSUE TITLE
Set up basic simulation environment in Gazebo

### ISSUE THREAD

**Issue by Goldob** [KNR-Selfie/selfie_carolocup2019#3]
- [x] Find or create a vehicle model with LIDAR, camera, odometry and Ackermann steering
- [x] Figure out a way to generate test tracks, e.g. using [this package](https://github.com/tum-phoenix/drive_sim_road_generation)
- [ ] Create a [Wiki](https://github.com/KNR-Selfie/selfie_carolocup2019/wiki) page with instruction for creating tracks and running simulation

**Comment by RafLit** [comment]
I downloaded and set up this package: [https://github.com/tum-phoenix/drive_sim_road_generation](url)
The package is able to generate 3 types of basic types of tracks:
1. a basic track with only turns
2. a track with obstacles and junctions
3. a track with with parking spots
One can add self-made presets to the package as well.
The tracks seemed really basic to me.
Gazebo 8 or 9 might be necessary to generate the tracks, while the default for ros kinetic is 7.

**Comment by jiaweiwuwu** [comment]
can you share your self -made presets Ring road to me :D —？

**Comment by AvaRat** [comment]
@jiaweiwuwu o jaki Ring road Ci chodzi?

**Comment by jiaweiwuwu** [comment]
Am 2019-04-22 00:38, schrieb AvaRat:

> @jiaweiwuwu [1] o jaki Ring track Ci chodzi? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

Hello,dear AvaRat,thank you very much for your reply,i was loooking
forward an Intersection junction(Crossroad) with Mountian setting as
enviroment.I hope you can help me . 

best regard.

  

Links:
------
[1] https://github.com/jiaweiwuwu
[2]
https://github.com/KNR-Selfie/selfie_carolocup2019/issues/3#issuecomment-485287306
[3]
